import type {
  Book,
  Category,
  User,
  LibraryStats,
  Inquiry,
  BorrowedBook,
  ReadingProgress,
  Video,
  VideoProgress,
} from "./types"

export const categories: Category[] = [
  { id: "1", name: "Fiction", description: "Novels and fictional stories", bookCount: 45, videoCount: 12 },
  { id: "2", name: "Science", description: "Scientific literature and research", bookCount: 32, videoCount: 18 },
  { id: "3", name: "Technology", description: "Programming and tech books", bookCount: 28, videoCount: 25 },
  { id: "4", name: "History", description: "Historical books and documentaries", bookCount: 23, videoCount: 8 },
  { id: "5", name: "Biography", description: "Life stories of notable people", bookCount: 18, videoCount: 6 },
  { id: "6", name: "Comedy", description: "Humorous books and entertainment", bookCount: 15, videoCount: 4 },
]

export const videos: Video[] = [
  {
    video_uuid: "VIDEO-A1B2C3",
    title: "Introduction to React Development",
    instructor: "Sarah Johnson",
    duration: "2h 45m",
    categories: ["Technology"],
    is_available: true,
    video_file: "/media/videos/react_intro.mp4",
    thumbnail: "/placeholder.svg?height=200&width=300",
    is_featured: true,
    access_permission: "AUTH",
    external_source: null,
    is_external: false,
    description:
      "Learn the fundamentals of React development from scratch. This comprehensive course covers components, state management, hooks, and modern React patterns.",
    upload_date: "2024-01-15",
    summary: "A beginner-friendly introduction to React development covering all essential concepts.",
    views: 1250,
    difficulty_level: "Beginner",
    language: "English",
  },
  {
    video_uuid: "VIDEO-D4E5F6",
    title: "Advanced JavaScript Concepts",
    instructor: "Michael Chen",
    duration: "3h 20m",
    categories: ["Technology"],
    is_available: true,
    video_file: "/media/videos/advanced_js.mp4",
    thumbnail: "/placeholder.svg?height=200&width=300",
    is_featured: true,
    access_permission: "ALL",
    external_source: null,
    is_external: false,
    description:
      "Deep dive into advanced JavaScript concepts including closures, prototypes, async programming, and ES6+ features.",
    upload_date: "2024-02-10",
    summary: "Master advanced JavaScript concepts to become a more effective developer.",
    views: 890,
    difficulty_level: "Advanced",
    language: "English",
  },
  {
    video_uuid: "VIDEO-G7H8I9",
    title: "The Science of Black Holes",
    instructor: "Dr. Emily Rodriguez",
    duration: "1h 15m",
    categories: ["Science"],
    is_available: true,
    video_file: "/media/videos/black_holes.mp4",
    thumbnail: "/placeholder.svg?height=200&width=300",
    is_featured: false,
    access_permission: "AUTH",
    external_source: null,
    is_external: false,
    description:
      "Explore the fascinating world of black holes, from their formation to their role in shaping the universe.",
    upload_date: "2024-03-05",
    summary: "An educational journey into the mysteries of black holes and space-time.",
    views: 2100,
    difficulty_level: "Intermediate",
    language: "English",
  },
  {
    video_uuid: "VIDEO-J1K2L3",
    title: "World War II Documentary Series",
    instructor: "Prof. David Thompson",
    duration: "4h 30m",
    categories: ["History"],
    is_available: true,
    video_file: "/media/videos/wwii_documentary.mp4",
    thumbnail: "/placeholder.svg?height=200&width=300",
    is_featured: true,
    access_permission: "ALL",
    external_source: null,
    is_external: false,
    description:
      "A comprehensive documentary series covering the major events, battles, and personalities of World War II.",
    upload_date: "2024-01-20",
    summary: "An in-depth exploration of World War II through archival footage and expert analysis.",
    views: 3200,
    difficulty_level: "Intermediate",
    language: "English",
  },
  {
    video_uuid: "VIDEO-M4N5O6",
    title: "Stand-Up Comedy Masterclass",
    instructor: "Comedy Central",
    duration: "2h 10m",
    categories: ["Comedy"],
    is_available: true,
    video_file: "/media/videos/comedy_masterclass.mp4",
    thumbnail: "/placeholder.svg?height=200&width=300",
    is_featured: false,
    access_permission: "AUTH",
    external_source: "https://youtube.com/watch?v=example",
    is_external: true,
    description:
      "Learn the art of stand-up comedy from professional comedians. Covers timing, delivery, writing, and stage presence.",
    upload_date: "2024-02-28",
    summary: "Master the fundamentals of stand-up comedy with tips from industry professionals.",
    views: 750,
    difficulty_level: "Beginner",
    language: "English",
  },
]

export const books: Book[] = [
  {
    id: "1",
    book_uuid: "BOOK-31FB89",
    title: "Rick And Morty, Destroyers or Saviours?",
    author: "Stephen Fry",
    publisher: "Comedy Central Books",
    categories: ["Science"],
    is_available: true,
    pdf_file: "/media/books/pdfs/rick_and_morty_analysis.pdf",
    cover_image: "/placeholder.svg?height=300&width=200",
    total_copies: 10,
    available_copies: 10,
    is_featured: true,
    book_type: "EBOOK",
    download_permission: "AUTH",
    is_ebook: true,
    available_status: "Available",
    external_source: null,
    is_external: false,
    description:
      "A deep dive into the philosophical implications of Rick and Morty's adventures across the multiverse. This book explores whether the duo's chaotic interventions ultimately help or harm the universe.",
    publication_date: "2023-05-15",
    summary: "An analytical look at the popular animated series through a philosophical lens.",
  },
  {
    id: "2",
    book_uuid: "BOOK-A1B2C3",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    publisher: "Scribner",
    categories: ["Fiction"],
    is_available: true,
    pdf_file: "/media/books/pdfs/great_gatsby.pdf",
    cover_image: "/placeholder.svg?height=300&width=200",
    total_copies: 15,
    available_copies: 12,
    is_featured: true,
    book_type: "EBOOK",
    download_permission: "ALL",
    is_ebook: true,
    available_status: "Available",
    external_source: null,
    is_external: false,
    description:
      "A classic American novel set in the Jazz Age, exploring themes of wealth, love, idealism, and moral decay in the American Dream.",
    publication_date: "1925-04-10",
    summary: "The story of Jay Gatsby's pursuit of the American Dream and his love for Daisy Buchanan.",
  },
  {
    id: "3",
    book_uuid: "BOOK-D4E5F6",
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    publisher: "MIT Press",
    categories: ["Technology"],
    is_available: true,
    pdf_file: "/media/books/pdfs/algorithms.pdf",
    cover_image: "/placeholder.svg?height=300&width=200",
    total_copies: 8,
    available_copies: 5,
    is_featured: false,
    book_type: "PHYSICAL",
    download_permission: "NONE",
    is_ebook: false,
    available_status: "Available",
    external_source: null,
    is_external: false,
    description:
      "Comprehensive guide to algorithms and data structures, covering fundamental concepts and advanced techniques used in computer science.",
    publication_date: "2009-07-31",
    summary: "The definitive guide to algorithms for computer science students and professionals.",
  },
  {
    id: "4",
    book_uuid: "BOOK-G7H8I9",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    publisher: "Bantam Books",
    categories: ["Science"],
    is_available: true,
    pdf_file: "/media/books/pdfs/brief_history_time.pdf",
    cover_image: "/placeholder.svg?height=300&width=200",
    total_copies: 12,
    available_copies: 8,
    is_featured: true,
    book_type: "EBOOK",
    download_permission: "AUTH",
    is_ebook: true,
    available_status: "Available",
    external_source: null,
    is_external: false,
    description:
      "A landmark volume in science writing by one of the great minds of our time, Stephen Hawking's book explores such profound questions as: How did the universe begin—and what made its start possible?",
    publication_date: "1988-04-01",
    summary: "An exploration of cosmology and the nature of time and space.",
  },
  {
    id: "5",
    book_uuid: "BOOK-J1K2L3",
    title: "Steve Jobs",
    author: "Walter Isaacson",
    publisher: "Simon & Schuster",
    categories: ["Biography"],
    is_available: true,
    pdf_file: "/media/books/pdfs/steve_jobs.pdf",
    cover_image: "/placeholder.svg?height=300&width=200",
    total_copies: 6,
    available_copies: 4,
    is_featured: false,
    book_type: "EBOOK",
    download_permission: "AUTH",
    is_ebook: true,
    available_status: "Available",
    external_source: null,
    is_external: false,
    description:
      "The exclusive biography of Apple co-founder Steve Jobs, based on more than forty interviews with Jobs conducted over two years.",
    publication_date: "2011-10-24",
    summary: "The definitive biography of one of the most influential figures in modern technology.",
  },
]

export const users: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    role: "user",
    registrationDate: "2024-01-15",
    booksRead: 12,
    videosWatched: 8,
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    role: "user",
    registrationDate: "2024-02-20",
    booksRead: 8,
    videosWatched: 15,
  },
  {
    id: "3",
    name: "Admin User",
    email: "admin@library.com",
    role: "admin",
    registrationDate: "2023-12-01",
    booksRead: 25,
    videosWatched: 30,
  },
]

export const inquiries: Inquiry[] = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice@example.com",
    subject: "Book Request",
    message: "Could you please add more books on machine learning?",
    date: "2024-01-15",
    status: "pending",
  },
  {
    id: "2",
    name: "Bob Wilson",
    email: "bob@example.com",
    subject: "Technical Issue",
    message: "I'm having trouble downloading the PDF files.",
    date: "2024-01-14",
    status: "resolved",
  },
]

export const borrowedBooks: BorrowedBook[] = [
  {
    id: "1",
    book_uuid: "BOOK-D4E5F6",
    user_id: "1",
    borrow_date: "2024-05-01",
    due_date: "2024-05-15",
    return_date: null,
    status: "borrowed",
    book: books.find((b) => b.book_uuid === "BOOK-D4E5F6")!,
    user: users.find((u) => u.id === "1")!,
  },
  {
    id: "2",
    book_uuid: "BOOK-J1K2L3",
    user_id: "2",
    borrow_date: "2024-04-20",
    due_date: "2024-05-04",
    return_date: null,
    status: "overdue",
    book: books.find((b) => b.book_uuid === "BOOK-J1K2L3")!,
    user: users.find((u) => u.id === "2")!,
  },
  {
    id: "3",
    book_uuid: "BOOK-A1B2C3",
    user_id: "1",
    borrow_date: "2024-04-15",
    due_date: "2024-04-29",
    return_date: null,
    status: "overdue",
    book: books.find((b) => b.book_uuid === "BOOK-A1B2C3")!,
    user: users.find((u) => u.id === "1")!,
  },
  {
    id: "4",
    book_uuid: "BOOK-G7H8I9",
    user_id: "3",
    borrow_date: "2024-05-05",
    due_date: "2024-05-19",
    return_date: null,
    status: "borrowed",
    book: books.find((b) => b.book_uuid === "BOOK-G7H8I9")!,
    user: users.find((u) => u.id === "3")!,
  },
  {
    id: "5",
    book_uuid: "BOOK-31FB89",
    user_id: "2",
    borrow_date: "2024-04-10",
    due_date: "2024-04-24",
    return_date: "2024-04-23",
    status: "returned",
    book: books.find((b) => b.book_uuid === "BOOK-31FB89")!,
    user: users.find((u) => u.id === "2")!,
  },
]

export const readingProgress: ReadingProgress[] = [
  {
    id: "1",
    book_uuid: "BOOK-31FB89",
    user_id: "1",
    progress: 45,
    last_read: "2024-05-10T14:30:00",
    book: books.find((b) => b.book_uuid === "BOOK-31FB89")!,
  },
  {
    id: "2",
    book_uuid: "BOOK-A1B2C3",
    user_id: "1",
    progress: 78,
    last_read: "2024-05-12T20:15:00",
    book: books.find((b) => b.book_uuid === "BOOK-A1B2C3")!,
  },
  {
    id: "3",
    book_uuid: "BOOK-G7H8I9",
    user_id: "2",
    progress: 23,
    last_read: "2024-05-09T10:45:00",
    book: books.find((b) => b.book_uuid === "BOOK-G7H8I9")!,
  },
]

export const videoProgress: VideoProgress[] = [
  {
    id: "1",
    video_uuid: "VIDEO-A1B2C3",
    user_id: "1",
    progress: 65,
    last_watched: "2024-05-10T16:45:00",
    video: videos.find((v) => v.video_uuid === "VIDEO-A1B2C3")!,
  },
  {
    id: "2",
    video_uuid: "VIDEO-D4E5F6",
    user_id: "1",
    progress: 30,
    last_watched: "2024-05-11T19:20:00",
    video: videos.find((v) => v.video_uuid === "VIDEO-D4E5F6")!,
  },
  {
    id: "3",
    video_uuid: "VIDEO-J1K2L3",
    user_id: "2",
    progress: 85,
    last_watched: "2024-05-09T21:15:00",
    video: videos.find((v) => v.video_uuid === "VIDEO-J1K2L3")!,
  },
]

export const libraryStats: LibraryStats = {
  totalBooks: 161,
  totalUsers: 1247,
  totalCategories: 6,
  totalEbooks: 98,
  totalVideos: 73,
}

export const libraryInfo = {
  name: "Central Digital Library",
  address: "123 Knowledge Street, Education City",
  phone: "+1 (555) 123-4567",
  email: "info@centrallibrary.com",
  timings: {
    weekdays: "9:00 AM - 8:00 PM",
    weekends: "10:00 AM - 6:00 PM",
  },
  description: "A modern digital library providing access to thousands of books, videos, and educational resources.",
}
